### ISSUE TITLE
no-unused-labels

### ISSUE THREAD

**Issue by shouston3** [dwyl/goodparts#167] opened 2016-09-20 16:28 UTC
http://eslint.org/docs/rules/no-unused-labels

NA we're not using labels

**Comment by eliascodes** [comment] 2016-09-21 11:11
closing duplicate of #166

**Comment by eliascodes** [comment] 2016-09-26 15:34
@SimonLab why was this re-opened? Its a duplicate of #166.

**Closed** 2016-09-26 15:36 UTC
Labels: best practices
